spring.application.name=pagos-service

server.port=8087

# Base de datos MySQL
spring.datasource.url=${PAGOS_DB_URL:jdbc:mysql://localhost:3306/megatech_pagos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${PAGOS_DB_USERNAME:root}
spring.datasource.password=${PAGOS_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Microservicios
services.pedidos.url=${PEDIDOS_URL:http://localhost:8086}