spring.application.name=pedidos-service

server.port=8086

# Base de datos MySQL
spring.datasource.url=${PEDIDOS_DB_URL:jdbc:mysql://localhost:3306/megatech_pedidos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${PEDIDOS_DB_USERNAME:root}
spring.datasource.password=${PEDIDOS_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Microservicios
services.carrito.url=${CARRITO_URL:http://localhost:8085}
services.inventario.url=${INVENTARIO_URL:http://localhost:8084}