spring.application.name=carrito-service

server.port=8085

# Base de datos MySQL / Amazon RDS
spring.datasource.url=${CARRITO_DB_URL:jdbc:mysql://localhost:3306/megatech_carrito?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${CARRITO_DB_USERNAME:root}
spring.datasource.password=${CARRITO_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Microservicios
services.inventario.url=${INVENTARIO_URL:http://localhost:8084}

# Seguridad JWT - Microsoft Entra ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_AUDIENCE}