# ==========================================================
# RabbitMQ Cluster - Megatech Comics
# ==========================================================

# Descubrimiento de nodos mediante configuración estática
cluster_formation.peer_discovery_backend = classic_config

# Nodos que formarán el cluster
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-2

# Puerto de administración
management.tcp.port = 15672