spring.application.name=editoriales-service

server.port=8083

spring.datasource.url=${EDITORIALES_DB_URL:jdbc:mysql://localhost:3306/megatech_editoriales?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${EDITORIALES_DB_USERNAME:root}
spring.datasource.password=${EDITORIALES_DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true